#! /usr/bin/env sh

HOME_DIRECTORY="${HOME}"
SCRIPT_DIRECTORY=$(dirname "$(dirname "$(readlink -f "$0")")")
LOCAL_BIN_DIRECTORY="${HOME_DIRECTORY}/.local/bin"

# Install fonts
echo "🖨️ Installing fonts"
cp "${SCRIPT_DIRECTORY}"/fonts/*.ttf ~/Library/Fonts
find ~/Library/Fonts/*.ttf -exec echo '  ✅ Installed {}' \;

# Install Homebrew
if ! (type brew > /dev/null 2>&1); then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi
export PATH="/opt/homebrew/bin:${PATH}"

# Install homebrew packages
echo "🍺 Installing stow with Homebrew"
brew install stow 2> /dev/null

# Install oh-my-zsh
echo "🐚 Installing oh-my-zsh"
"${SCRIPT_DIRECTORY}"/oh-my-zsh/install.sh

# Install dotfiles with stow
echo "⚫ Installing dotfiles with stow"
find "${SCRIPT_DIRECTORY}/dotfiles" -type d -depth 1 -exec basename {} \; | while read -r category; do
    echo "  ⌛ Working on $category"
    stow -t "$HOME_DIRECTORY" -d "${SCRIPT_DIRECTORY}/dotfiles" -R "$category"
done

# Install executables with stow
echo "❗ Installing executables with stow"
mkdir -p "${LOCAL_BIN_DIRECTORY}"
stow -t "${LOCAL_BIN_DIRECTORY}" -d "${SCRIPT_DIRECTORY}" -R executables
find "${LOCAL_BIN_DIRECTORY}" -type f -depth 1 | while read -r executable; do
    echo "  ✅ Installed $executable"
done

# Install homebrew packages
echo "🍺 Installing Homebrew packages"
"${SCRIPT_DIRECTORY}"/homebrew/install.sh

# Fix application permissions
sudo chown -R "$(whoami):admin" /Applications 2> /dev/null

# Enable touchbar sudo
TOUCHBAR_STRING=$(grep "sufficient" /etc/pam.d/sudo | grep "auth" | head -n 1 | sed "s/pam_.*.so/pam_tid.so/")
pam_sudo_target=$(mktemp)
(cat /etc/pam.d/sudo; echo "$TOUCHBAR_STRING") | sort | uniq > "$pam_sudo_target"
echo "Enabling touchbar sudo in /etc/pam.d/sudo"
# shellcheck disable=SC2024
sudo tee /etc/pam.d/sudo < "$pam_sudo_target" > /dev/null
grep "pam_tid.so" /etc/pam.d/sudo > /dev/null && echo "Touchbar sudo ENABLED" || echo "Touchbar sudo NOT ENABLED"
rm -rf "$pam_sudo_target"

# Print instructional messages
echo ""
echo "MANUAL STEPS"
echo ""
echo "In case of font problems in zsh, see here: https://gist.github.com/kevin-smets/8568070 and https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k"
echo ""
echo "Use the following colour-schemes in iTerm2"
echo "* zsh should use 'tango-dark-tweaked' (import from the iterm directory)"
echo "* Powershell should use 'shades-of-purple' (import from the iterm directory)"
