#! /usr/bin/env sh

HATCH_VENV_DIR="${HOME}/Library/Application Support/hatch/env/virtual"
PYENV_VENV_DIR="${HOME}/.pyenv/versions"

find "$HATCH_VENV_DIR" -type d -depth 1 | while read -r VENV_PATH; do
    VENV_NAME=$(echo "$VENV_PATH" | rev | cut -d '/' -f 1 | rev);
    TARGET="${PYENV_VENV_DIR}/${VENV_NAME}"
    # If the target already exists as a symlink then remove it
    if [ -L "$TARGET" ]; then
        echo "🧼 Removing existing link to '$TARGET'"
        rm "$TARGET";
    fi
    # If the target does not exist then create a symlink
    if [ ! -e "$TARGET" ]; then
        echo "✅ Creating link to '$TARGET'"
        VENV_FULL_PATH=$(find "$VENV_PATH" -name $VENV_NAME | tail -n 1)
        ln -s "$VENV_FULL_PATH" "${PYENV_VENV_DIR}/${VENV_NAME}";
    fi
done
