#! /usr/bin/env sh

# Find hatch venv directory and verify it exists
HATCH_VENV_PATH=$(hatch env find)
if [ ! -e "$HATCH_VENV_PATH" ]; then echo "No hatch environment is associated with this directory"; exit 1; fi

# Get global pyenv directory and construct target name
PYENV_VENV_DIR="$(pyenv root)/versions"
VENV_NAME=$(pwd | rev | cut -d '/' -f 1 | rev)
TARGET="${PYENV_VENV_DIR}/${VENV_NAME}"

# If the target already exists as a symlink then remove it
if [ -L "$TARGET" ]; then
    echo "🧼 Removing existing link to '$TARGET'"
    rm "$TARGET";
fi

# If the target does not exist then create a symlink
if [ ! -e "$TARGET" ]; then
    echo "✅ Creating link to '$TARGET'"
    ln -s "$HATCH_VENV_PATH" "${PYENV_VENV_DIR}/${VENV_NAME}";
fi

# Set this as the local pyenv version
echo "$VENV_NAME" > .python-version