#! /usr/bin/env sh

POETRY_VENV_DIR="${HOME}/Library/Caches/pypoetry/virtualenvs"
PYENV_VENV_DIR="${HOME}/.pyenv/versions"

find "$POETRY_VENV_DIR" -type d -depth 1 | while read -r VENV_PATH; do
    VENV_NAME=$(echo "$VENV_PATH" | rev | cut -d '-' -f 3-999 | cut -d '/' -f 1 | rev);
    TARGET="${PYENV_VENV_DIR}/${VENV_NAME}"
    # If the target already exists as a symlink then remove it
    if [ -e "$TARGET" ] && [ -L "$TARGET" ]; then
        echo "🧼 Removing existing link to '$TARGET'"
        rm "$TARGET";
    fi
    # If the target does not exist then create a symlink
    if [ ! -e "$TARGET" ]; then
        echo "✅ Creating link to '$TARGET'"
        ln -s "$VENV_PATH" "${PYENV_VENV_DIR}/${VENV_NAME}";
    fi
    # Symlink poetry executable from pyenv
    POETRY_EXECUTABLE_SOURCE="$(realpath $(pyenv which poetry))"
    if [ -e "$POETRY_EXECUTABLE_SOURCE" ]; then
        POETRY_EXECUTABLE_TARGET="${VENV_PATH}/bin/poetry"
        if [ -e "$POETRY_EXECUTABLE_TARGET" ]; then
            echo "🙅 Poetry already exists in '$TARGET'"
        else
            ln -s "$POETRY_EXECUTABLE_SOURCE" "$POETRY_EXECUTABLE_TARGET"
            echo "✅ Creating poetry symlink in '$TARGET'"
        fi
    fi
done
